apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-c
  labels:
    app: dep-c
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-c
  template:
    metadata:
      labels:
        app: app-c
    spec:
      containers:
      - name: myapp
        image: vplauzon/get-started:part2-no-redis
        ports:
        - containerPort: 80
