apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-g
  labels:
    app: dep-g
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-g
  template:
    metadata:
      labels:
        app: app-g
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key:  app
                operator:  In
                values:
                - app-g
            topologyKey: failure-domain.beta.kubernetes.io/zone
          - labelSelector:
              matchExpressions:
              - key:  app
                operator:  In
                values:
                - app-g
            topologyKey: azure-update-domain
      containers:
      - name: myapp
        image: vplauzon/get-started:part2-no-redis
        ports:
        - containerPort: 80
