apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-f
  labels:
    app: dep-f
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-f
  template:
    metadata:
      labels:
        app: app-f
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key:  app
                operator:  In
                values:
                - app-f
            topologyKey: azure-update-domain
      containers:
      - name: myapp
        image: vplauzon/get-started:part2-no-redis
        ports:
        - containerPort: 80